# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Azure Pipelines

steps:
- task: TerraformInstaller@0
  displayName: 'Use Terraform latest'

- task: TerraformTaskV1@0
  displayName: 'Terraform : INIT'
  inputs:
    backendServiceArm: 'Jonnychipz-TFSPN'
    backendAzureRmResourceGroupName: 'jonnychipz-infra'
    backendAzureRmStorageAccountName: jonnychipztstate
    backendAzureRmContainerName: tstate
    backendAzureRmKey: '77Q4LUB5o9wRdbPYDt+0kGZP+L8Sj9E/FNXg7lZBQS5z3mLod5cyan4wA19CR1SmlqIRUFQfhuQrPVaGzNhjGw=='

- task: TerraformTaskV1@0
  displayName: 'Terraform : PLAN'
  inputs:
    command: plan
    environmentServiceNameAzureRM: 'Jonnychipz-TFSPN'

- task: TerraformTaskV1@0
  displayName: 'Terraform : VAL & APPLY'
  inputs:
    command: apply
    environmentServiceNameAzureRM: 'Jonnychipz-TFSPN'
